git:
  overrideGpg: true
gui:
  theme:
    activeBorderColor:
    - '#815c94'
    - bold
    cherryPickedCommitBgColor:
    - '#d6d6d6'
    cherryPickedCommitFgColor:
    - '#80766e'
    defaultFgColor:
    - '#4a4035'
    inactiveBorderColor:
    - '#80766e'
    optionsTextColor:
    - '#2f2f35'
    searchingActiveBorderColor:
    - '#918072'
    - bold
    selectedLineBgColor:
    - '#80766e'
    unstagedChangesColor:
    - '#c04851'
