[completion.active]
bg = "#80766e"
fg = "#c08eaf"

[completion.border]
fg = "#815c94"

[completion.inactive]
fg = "#4a4035"

[[filetype.rules]]
fg = "#2b73af"
mime = "image/*"

[[filetype.rules]]
fg = "#d6a01d"
mime = "video/*"

[[filetype.rules]]
fg = "#d6a01d"
mime = "audio/*"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/zip"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/gzip"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/tar"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/bzip"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/bzip2"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/7z-compressed"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/rar"

[[filetype.rules]]
fg = "#c08eaf"
mime = "application/xz"

[[filetype.rules]]
fg = "#428675"
mime = "application/doc"

[[filetype.rules]]
fg = "#428675"
mime = "application/pdf"

[[filetype.rules]]
fg = "#428675"
mime = "application/rtf"

[[filetype.rules]]
fg = "#428675"
mime = "application/vnd.*"

[[filetype.rules]]
bold = true
fg = "#815c94"
mime = "inode/directory"

[[filetype.rules]]
fg = "#4a4035"
mime = "*"

[help.desc]
fg = "#4a4035"

[help.footer]
fg = "#4a4035"

[help.hovered]
bg = "#80766e"
fg = "#4a4035"

[help.on]
fg = "#c08eaf"

[help.run]
fg = "#2b73af"

[input.border]
fg = "#815c94"

[input.selected]
bg = "#80766e"

[input.title]
fg = "#4a4035"

[input.value]
fg = "#4a4035"

[mgr]
syntect_theme = "/nix/store/hbkccacyrpwjdwy4dbs6sgnx8y4ym9k5-base16-chinoiserie.tmTheme"

[mgr.border_style]
fg = "#918072"

[mgr.count_copied]
bg = "#428675"
fg = "#ffffff"

[mgr.count_cut]
bg = "#c04851"
fg = "#ffffff"

[mgr.count_selected]
bg = "#d6a01d"
fg = "#ffffff"

[mgr.cwd]
fg = "#2b73af"

[mgr.find_keyword]
bold = true
fg = "#428675"

[mgr.find_position]
fg = "#c08eaf"

[mgr.hovered]
bg = "#d6d6d6"
bold = true

[mgr.marker_copied]
bg = "#428675"
fg = "#428675"

[mgr.marker_cut]
bg = "#c04851"
fg = "#c04851"

[mgr.marker_selected]
bg = "#d6a01d"
fg = "#d6a01d"

[mgr.preview_hovered]
bg = "#d6d6d6"
bold = true

[mode.normal_alt]
bg = "#ffffff"
fg = "#815c94"

[mode.normal_main]
bg = "#815c94"
bold = true
fg = "#ffffff"

[mode.select_alt]
bg = "#ffffff"
fg = "#428675"

[mode.select_main]
bg = "#428675"
bold = true
fg = "#ffffff"

[mode.unset_alt]
bg = "#ffffff"
fg = "#945833"

[mode.unset_main]
bg = "#945833"
bold = true
fg = "#ffffff"

[pick.active]
fg = "#c08eaf"

[pick.border]
fg = "#815c94"

[pick.inactive]
fg = "#4a4035"

[status.perm_exec]
fg = "#428675"

[status.perm_read]
fg = "#d6a01d"

[status.perm_sep]
fg = "#2b73af"

[status.perm_type]
fg = "#815c94"

[status.perm_write]
fg = "#c04851"

[status.progress_error]
bg = "#ffffff"
fg = "#c04851"

[status.progress_label]
bg = "#ffffff"
fg = "#4a4035"

[status.progress_normal]
bg = "#ffffff"
fg = "#4a4035"

[tabs.active]
bg = "#815c94"
bold = true
fg = "#ffffff"

[tabs.inactive]
bg = "#e0e0e0"
fg = "#815c94"

[tasks.border]
fg = "#815c94"

[tasks.hovered]
bg = "#80766e"
fg = "#4a4035"

[tasks.title]
fg = "#4a4035"

[which.cand]
fg = "#2b73af"

[which.desc]
fg = "#4a4035"

[which.mask]
bg = "#d6d6d6"

[which.rest]
fg = "#945833"

[which.separator_style]
fg = "#918072"
