[colors.bright]
black = "#80766e"
blue = "#815c94"
cyan = "#2b73af"
green = "#428675"
magenta = "#c08eaf"
red = "#c04851"
white = "#131124"
yellow = "#d6a01d"

[colors.cursor]
cursor = "#4a4035"
text = "#ffffff"

[colors.normal]
black = "#ffffff"
blue = "#815c94"
cyan = "#2b73af"
green = "#428675"
magenta = "#c08eaf"
red = "#c04851"
white = "#4a4035"
yellow = "#d6a01d"

[colors.primary]
background = "#ffffff"
bright_foreground = "#131124"
foreground = "#4a4035"

[colors.selection]
background = "#d6d6d6"
text = "#4a4035"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
opacity = 1.0
decorations = "none"

[window.padding]
x = 2
y = 2
